---
name: Algorithm-Damm
version: 1.001.002
author:
  - 'Brian T. Wightman <MidLifeXis@wightmanfam.org>'
abstract: Calculate the Damm error correction check digit.
license: perl
resources:
  license: ~
configure_requires:
  Module::Build: 0
requires:
  perl: 5.6.0
build_requires:
  Test::More: 0
provides:
  Algorithm::Damm:
    file: lib/Algorithm/Damm.pm
    version: 1.001.002
generated_by: Module::Build version 0.32
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
